[package]
name = "iban"
version = "1.0.0"
authors = ["SuRu <33urus@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
clap = "2.33.3"
rand = "0.8.3"